### ISSUE TITLE
What exactly is the JS object of an module block?

### ISSUE THREAD

**Issue by surma** [tc39/proposal-js-module-blocks#1]
```js
const m = module { /* ... */ }

typeof m // ?
Object.getPrototypeOf(m) // ?
```

**Comment by Jack-Works** [comment]
typeof m // object
Object.getPrototypeOf(m) // a new intrinsic, non-constructable class Module

**Comment by littledan** [comment]
One possible solution: They are just strings. There's a new host hook to return a string, which is then expected to work appropriately if it's used as a module specifier. WDYT?

**Comment by Jack-Works** [comment]
So it's like a blob URL?

**Comment by littledan** [comment]
> So it's like a blob URL?

Probably something like that, but there are some differences around the edges vs blobs today (e.g., `import.meta.url`).

**Comment by kriskowal** [comment]
I propose that the representation of a module be a `StaticModuleRecord` as proposed on the Compartments (module loader API) proposal. https://github.com/tc39/proposal-compartments

To be consistent, we would amend the argument of `import(specifier:string):Promise<Namespace>` to `string | StaticModuleRecord` and switch the behavior on the type. We would revise `import` in all places.

If given a `StaticModuleRecord`, the module would be executed and the namespace would not be cached. I believe that behavior is more useful than a singleton.

If the `module` block were captured as a string:

- it would need to be a valid module specifier, which in turn would imply
- its content is also its cache key, which in turn would imply
- it would be cached and produce a singleton, which would in turn imply
- they could not be executed multiple times.

There would certainly need to be a serialization and that could be just the content string. `new StaticModuleRecord(string)` would rehydrate it.

The serialization will need to capturer `import.meta.url`. I propose that could be carried by a final `//#sourceURL` and should override any such comment that’s already there.

**Comment by surma** [comment]
I have to catch up on the compartments proposal, so I don’t have an opinion on your typing suggestion yet. 

Wrt to caching:

> they could not be executed multiple times.

This seems like _desired_ behavior to me. AFAIU, modules can only get executed once currently. This will create a single `console.log`:

```js
// mymodule.mjs
console.log("Module exection!");

// main.mjs
import("./mymodule.mjs");
import("./mymodule.mjs");
import("./mymodule.mjs");
```

I don’t think module blocks should deviate from this behavior.

**Comment by kriskowal** [comment]
That would certainly be consistent, if possibly less useful. I do not have strong feelings one way or the other.

I’d propose some design invariants worth preserving:

- The full response module specifier is the cache key.
- The module block should inherit the full response module specifier
- At least with Compartments, particularly in XS, the full response module specifier is not necessarily the same as the source URL or response URL. The relationship between the module specifier domain and the module location domain is intrinsic to the compartment.
- The `//#sourceURL` is surfaced in Error stack frames and in debuggers but is not necessarily the same as the full request module specifier, full response module specifier, or source response location.
- Within a module block, the sourceURL and line numbering should be inherited from the parent module. A `//#sourceURL` at the end of the module block should not be captured in the serialization of a module block, or should be replaced with the actual source URL and somehow also carry the line number offset. That could imply an inline `//#sourceMapURL` with a data blob, or some other mechanism.
- So, the value of a module block needs to at least capture the source, its location, and the full module specifier for import specifier resolution, and the line number offset.
- If the module value is a string, it’ll need to be the valid, unique module specifier for the module and be suitable as a referrer specifier that is equivalent to the containing module specifier for purposes of resolving its contained import specifiers.

**Comment by kriskowal** [comment]
> The serialization will need to capturer `import.meta.url`. I propose that could be carried by a final `//#sourceURL` and should override any such comment that’s already there.

I’m recanting this observation. Above, I thought myself out of the idea because the values are not necessarily the same.

**Comment by littledan** [comment]
@kriskowal How would you feel about omitting the `staticImports` method in this proposal, and adding it as part of the compartments proposal, but still agreeing to reuse the same prototype across both proposals? I think I agree with you that these are conceptually the same thing and should be represented with the same class.

I think I agree with your design invariants, though I'm not really sure what you mean by the definition of some of these terms (e.g., "full request module specifier"). Let's discuss these invariants further in an upcoming SES call.

**Comment by kriskowal** [comment]
The details about how imports and exports are reflected on static module records in the Compartments proposal is still fluid at this time. I’ve got informal consensus on giving the record properties like `imports`, `exports`, `reexports`, and `reexportsAll`. Oddly, there’s no immediate mechanical need for these to be visible in either proposal as-designed. I have no strong feelings about these details. https://docs.google.com/presentation/d/15fqj-CGO9zZScvZ-kdePQJDh3_uCSKQcRq3-o3Q5P5k/edit#slide=id.g98ebfeffc9_0_178

I plan to add this glossary to the Compartment proposal https://docs.google.com/presentation/d/15fqj-CGO9zZScvZ-kdePQJDh3_uCSKQcRq3-o3Q5P5k/edit#slide=id.ga000696b57_0_0

- “full vs partial” are a logical distinction that’s meaningful to the loader, such that `resolveHook(Partial, Full) : Full``resolveHook` is synchronous.
- “request vs response” are physical distinctions that account for redirects and canonicalization, which may be asynchronous.

**Comment by littledan** [comment]
@kriskowal and I recently discussed this issue with others in an SES call, concluding that module blocks and StaticModuleRecord are fundamentally representing the same thing (or at least should be thought of as implementers of the same interface), and that it's reasonable for module blocks to, initially, lack these kinds of introspection methods.

**Comment by littledan** [comment]
There's a pretty concrete answer to this question spelled out in the specification draft of #24. I think we can close this issue when that patch lands, unless people have concerns.

**Comment by littledan** [comment]
Closing due to https://github.com/tc39/proposal-js-module-blocks/pull/24
