### ISSUE TITLE
Allow await inline modules?

### ISSUE THREAD

**Issue by proteriax** [tc39/proposal-js-module-blocks#17]
Specifically,

```js
const i18n = await module {
  export function t(key) {
  }
}
```

Instead of having to create an intermediate variable.

**Comment by nicolo-ribaudo** [comment]
You can already avoid the intermediate variable with
```js
const i18n = await import(module {
  export function t(key) {
  }
});
```

**Comment by surma** [comment]
Yeah, what @nicolo-ribaudo said. Being able to await the module itself to get an instance would create serious questions about the underlying types and have implications wrt module caching. I
