### ISSUE TITLE
CSP interaction

### ISSUE THREAD

**Issue by koto** [tc39/proposal-js-module-blocks#28]
The README [claims](https://github.com/tc39/proposal-js-module-blocks#integration-with-csp) that modules "cannot be a vector for injection attacks, and they are not blocked by [CSP's eval blocking] condition".

However the [spec text](https://tc39.es/proposal-js-module-blocks/#sec-moduleblock) uses `HostEnsureCanCompileStrings` - as is, using the module blocks in web applications requires those applications to use `unsafe-eval`, if they use CSP. 

Which behavior is the expected one?

**Comment by surma** [comment]
In the current iteration of the spec, `HostEnsureCanCompileStrings` is only called when you use the `ModuleBlocks` constructor, which is analogous to the `Function` constructor, which indeed should be tied to CSP. 

Module Blocks literals not have that step.
