### ISSUE TITLE
Can module blocks appear in non-module scripts?

### ISSUE THREAD

**Issue by jakearchibald** [tc39/proposal-js-module-blocks#37]
```html
<script>
  const module = module { export default 42; }
  import(module);
</script>
```

Does the above work?

**Comment by Jack-Works** [comment]
Yes

**Comment by surma** [comment]
Yeah, since `import()` is available in non-module scripts, I don’t see why module blocks should not be available.

**Comment by jakearchibald** [comment]
Sounds good. Ohhh, but…

```html
<script>
  console.log(import.meta.url);
</script>
```

The above throws with `"SyntaxError: Cannot use 'import.meta' outside a module"`. But would this work?:

```html
<script>
  const module = module { export default = import.meta.url; }
  import(module).then(console.log);
</script>
```

Relative imports work in classic scripts, so there isn't an issue knowing what script they're in. I'm not sure why `import.meta.url` throws in classic scripts.

**Comment by ljharb** [comment]
Because classic scripts aren’t importable. import.meta.url is supposed to be the specifier you used to import the current module.

**Comment by jakearchibald** [comment]
Given that, it isn't clear to me if the above example should work.

**Comment by ljharb** [comment]
Per #26, i think it should be nullish, but it should work regardless of what its value is in the module block, because the module block is a Module, not a Script.

**Comment by littledan** [comment]
Yeah, we'll have to work out the `import.meta.url` in the HTML integration PR. There are a lot of possible answers here.

**Comment by Jamesernator** [comment]
Relative imports (`import("./relative-specifier.js")`) already work, it'd be a bit weird if `import.meta.url` was anything other than the same URL that `import(...)` uses otherwise `import()` within the module block would be different from `import()` outside the block.

**Comment by nicolo-ribaudo** [comment]
Yes, module blocks can appear in non-module scripts. `import.meta` is available in module blocks declared inside scripts, because module blocks are modules and `import.meta` is always available in modules.

The discussion about the `import.meta.url` value is in https://github.com/tc39/proposal-js-module-blocks/issues/26.
