### ISSUE TITLE
Asset on expected execution context

### ISSUE THREAD

**Issue by jkrems** [tc39/proposal-js-module-blocks#49]
There are a couple of situations where tools (or developers) may like to express where a module block is expected to be executed. For example:

1. Preventing accidental use of a module block that expects a worker context in a document context.
2. Override lint rules for module blocks targeting a certain environment.
3. Use proper type inference for type checking or optimizations.

I think it would be great if module blocks provided a way to annotate a block with its expected context. Straw proposal:

```js
// In a document context:
let moduleBlock = module assert { context: ['worker'] } {
  export let y = 1;
};
// This would reject without evaluating the module:
let moduleExports = await import(moduleBlock);
// This would work fine:
let worker = new Worker(workerBlock, {type: "module"});
```

I picked that straw syntax because in a way it's a "reverse import assertion".

**Comment by surma** [comment]
ES Modules don’t have this functionality of expressing their expected context, so I don’t think we should add it to module blocks (... without adding it everywhere else, too). That should be a separate proposal.
