### ISSUE TITLE
.toString() behavior

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-js-module-blocks#5]
```js
const code = module {
    console.log('hello')
}

code.toString()
```

`[object Module]` or `\n    console.log('hello')\n`?

**Comment by littledan** [comment]
I like the idea of returning `"module {\n    console.log('hello')\n}"` -- this would be analogous to Function.prototype.toString.

**Comment by littledan** [comment]
#24 codifies the behavior in https://github.com/tc39/proposal-js-module-blocks/issues/5#issuecomment-737387579

**Comment by littledan** [comment]
Closing due to https://github.com/tc39/proposal-js-module-blocks/pull/24
