### ISSUE TITLE
Useful for code splitting

### ISSUE THREAD

**Issue by zdila** [tc39/proposal-js-module-blocks#52]
Maybe it would be worth mentioning that one usecase could be a code splitting (eg. with webpack).

**Comment by nicolo-ribaudo** [comment]
For code splitting you can already use normal modules (one module per file/chunk).

This could be useful for the opposite: to easily put multiple modules in the same file/chunk.

**Comment by surma** [comment]
Please see the [Bundling section](https://github.com/tc39/proposal-js-module-blocks#can-module-blocks-help-with-bundling) in the FAQ of the README :)

**Comment by zdila** [comment]
Putting multiple modules in the same chunk is default behaviour of Webpack (ie. it compiles many source js files to a single one).

What I am missing is to have a single source js file compiled by webpack to multiple chunks.

**Comment by nicolo-ribaudo** [comment]
Oh something like this?

```js
element.addEventListener("click", () => import(clickHandler).then(m => m.default()));

// This module is not used immediately, we can tell webpack to put it in a separate lazy-loaded chunk.
const clickHandler = module {
  export default function () {
    console.log("Clicked!");
  }
}
```

**Comment by zdila** [comment]
@nicolo-ribaudo exactly

**Comment by surma** [comment]
Again, if you look at the [READAME Bundling section](https://github.com/tc39/proposal-js-module-blocks#can-module-blocks-help-with-bundling) I linked earlier, you’ll see why it works in simple situations, but not as a _general_ solution for bundling.
